// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.3.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bovespa_mbo_sbe
{
namespace detail
{
namespace types
{

enum class enum_24 : ::std::uint8_t
{
    NO_AGGRESSOR = 0,
    BUY = 1,
    SELL = 2
};

template<typename Visitor>
SBEPP_CPP14_CONSTEXPR void tag_invoke(
    ::sbepp::detail::visit_tag, enum_24 e, Visitor& visitor) noexcept
{
    switch(e)
    {
    case enum_24::NO_AGGRESSOR:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::AggressorSide::NO_AGGRESSOR{});
        break;
    case enum_24::BUY:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::AggressorSide::BUY{});
        break;
    case enum_24::SELL:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::AggressorSide::SELL{});
        break;
    default:
        visitor.on_enum_value(e, ::sbepp::unknown_enum_value_tag{});
    }
}


} // namespace types
} // namespace detail

namespace types
{
using AggressorSide = ::bovespa_mbo_sbe::detail::types::enum_24;
} // namespace types
} // namespace bovespa_mbo_sbe

namespace sbepp
{

template<>
class enum_traits<::bovespa_mbo_sbe::schema::types::AggressorSide>
{
public:
    static constexpr const char* name() noexcept
    {
        return "AggressorSide";
    }

    static constexpr const char* description() noexcept
    {
        return "Which side is aggressor of this trade.";
    }

    using encoding_type = ::std::uint8_t;
    
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bovespa_mbo_sbe::types::AggressorSide;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::types::AggressorSide>
{
    using type = ::bovespa_mbo_sbe::schema::types::AggressorSide;
};


template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::AggressorSide::NO_AGGRESSOR>
{
public:
    static constexpr const char* name() noexcept
    {
        return "NO_AGGRESSOR";
    }

    static constexpr const char* description() noexcept
    {
        return "Trade has no aggressor.";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::AggressorSide value() noexcept
    {
        return ::bovespa_mbo_sbe::types::AggressorSide::NO_AGGRESSOR;
    }
};

template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::AggressorSide::BUY>
{
public:
    static constexpr const char* name() noexcept
    {
        return "BUY";
    }

    static constexpr const char* description() noexcept
    {
        return "Buy.";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::AggressorSide value() noexcept
    {
        return ::bovespa_mbo_sbe::types::AggressorSide::BUY;
    }
};

template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::AggressorSide::SELL>
{
public:
    static constexpr const char* name() noexcept
    {
        return "SELL";
    }

    static constexpr const char* description() noexcept
    {
        return "Sell.";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::AggressorSide value() noexcept
    {
        return ::bovespa_mbo_sbe::types::AggressorSide::SELL;
    }
};

}  // namespace sbepp

SBEPP_WARNINGS_ON();
