// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.3.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bovespa_mbo_sbe
{
namespace detail
{
namespace types
{

template<typename Byte>
using type_6 = ::sbepp::detail::static_array_ref<
    Byte, char, 3, ::bovespa_mbo_sbe::schema::types::Currency>;

} // namespace types
} // namespace detail

namespace types
{

    template<typename Byte>
    using Currency = ::bovespa_mbo_sbe::detail::types::type_6<Byte>;

} // namespace types
} // namespace bovespa_mbo_sbe

namespace sbepp
{

template<>
class type_traits<::bovespa_mbo_sbe::schema::types::Currency>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Currency";
    }

    static constexpr const char* description() noexcept
    {
        return "3-letter alphabetic ISO Currency Codes (ISO 4217). Example: BRL, USD.";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = char;
    
    
    static constexpr length_t length() noexcept
    {
        return 3;
    }
    
    
    
    static constexpr const char* semantic_type() noexcept
    {
        return "Currency";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    
    template<typename Byte>
    using value_type = ::bovespa_mbo_sbe::types::Currency<Byte>;

};



}  // namespace sbepp

SBEPP_WARNINGS_ON();
