// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.3.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bovespa_mbo_sbe
{
namespace detail
{
namespace types
{


class type_43
    : public ::sbepp::detail::required_base<::std::uint16_t, type_43>
{
public:
    using ::sbepp::detail::required_base<
        ::std::uint16_t, type_43>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {65534};
    }
};

class type_44
    : public ::sbepp::detail::required_base<::std::uint16_t, type_44>
{
public:
    using ::sbepp::detail::required_base<
        ::std::uint16_t, type_44>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {65534};
    }
};


template<typename Byte>
class composite_4 : public ::sbepp::detail::composite_base<Byte>
{
public:
    using ::sbepp::detail::composite_base<Byte>::composite_base;
    using ::sbepp::detail::composite_base<Byte>::operator();

    SBEPP_CPP20_CONSTEXPR ::bovespa_mbo_sbe::detail::types::type_43 messageLength() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bovespa_mbo_sbe::detail::types::type_43, ::bovespa_mbo_sbe::detail::types::type_43::value_type, ::sbepp::endian::little>(*this, 0);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void messageLength(::bovespa_mbo_sbe::detail::types::type_43 v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 0, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bovespa_mbo_sbe::detail::types::type_44 encodingType() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bovespa_mbo_sbe::detail::types::type_44, ::bovespa_mbo_sbe::detail::types::type_44::value_type, ::sbepp::endian::little>(*this, 2);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void encodingType(::bovespa_mbo_sbe::detail::types::type_44 v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 2, v.value());
    }


    constexpr std::size_t
        operator()(::sbepp::detail::size_bytes_tag) const noexcept
    {
        return 4;
    }

    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_tag, Visitor& v, Cursor&) const
    {
        return v.template on_composite(*this, ::bovespa_mbo_sbe::schema::types::FramingHeader{});
    }


    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_children_tag, Visitor& v, Cursor&) const
    {
        return v.template on_type(this->messageLength(), ::bovespa_mbo_sbe::schema::types::FramingHeader::messageLength{})
||v.template on_type(this->encodingType(), ::bovespa_mbo_sbe::schema::types::FramingHeader::encodingType{});
    }

};

} // namespace types
} // namespace detail

namespace types
{

    template<typename Byte>
    using FramingHeader = ::bovespa_mbo_sbe::detail::types::composite_4<Byte>;

} // namespace types
} // namespace bovespa_mbo_sbe

namespace sbepp
{

template<>
class type_traits<::bovespa_mbo_sbe::schema::types::FramingHeader::messageLength>
{
public:
    static constexpr const char* name() noexcept
    {
        return "messageLength";
    }

    static constexpr const char* description() noexcept
    {
        return "Overall message length including headers to support framing.";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::uint16_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {0};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bovespa_mbo_sbe::detail::types::type_43;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::detail::types::type_43>
{
    using type = ::bovespa_mbo_sbe::schema::types::FramingHeader::messageLength;
};


template<>
class type_traits<::bovespa_mbo_sbe::schema::types::FramingHeader::encodingType>
{
public:
    static constexpr const char* name() noexcept
    {
        return "encodingType";
    }

    static constexpr const char* description() noexcept
    {
        return "Identifier of the encoding used in the message payload.";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::uint16_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {2};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bovespa_mbo_sbe::detail::types::type_44;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::detail::types::type_44>
{
    using type = ::bovespa_mbo_sbe::schema::types::FramingHeader::encodingType;
};


template<>
class composite_traits<::bovespa_mbo_sbe::schema::types::FramingHeader>
{
public:
    static constexpr const char* name() noexcept
    {
        return "FramingHeader";
    }

    static constexpr const char* description() noexcept
    {
        return "Framing Header (Compact SOFH).";
    }

    

    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }

    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::bovespa_mbo_sbe::types::FramingHeader<Byte>;


    static constexpr std::size_t size_bytes() noexcept
    {
        return 4;
    }
};

template<typename Byte>
struct traits_tag<::bovespa_mbo_sbe::types::FramingHeader<Byte>>
{
    using type = ::bovespa_mbo_sbe::schema::types::FramingHeader;
};


}  // namespace sbepp

SBEPP_WARNINGS_ON();
