// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.3.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bovespa_mbo_sbe
{
namespace detail
{
namespace types
{

enum class enum_3 : ::std::uint8_t
{
    TRADE_TYPE_ELIGIBILITY = 24,
    GTD_GTC_ELIGIBILITY = 34
};

template<typename Visitor>
SBEPP_CPP14_CONSTEXPR void tag_invoke(
    ::sbepp::detail::visit_tag, enum_3 e, Visitor& visitor) noexcept
{
    switch(e)
    {
    case enum_3::TRADE_TYPE_ELIGIBILITY:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::InstrAttribType::TRADE_TYPE_ELIGIBILITY{});
        break;
    case enum_3::GTD_GTC_ELIGIBILITY:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::InstrAttribType::GTD_GTC_ELIGIBILITY{});
        break;
    default:
        visitor.on_enum_value(e, ::sbepp::unknown_enum_value_tag{});
    }
}


} // namespace types
} // namespace detail

namespace types
{
using InstrAttribType = ::bovespa_mbo_sbe::detail::types::enum_3;
} // namespace types
} // namespace bovespa_mbo_sbe

namespace sbepp
{

template<>
class enum_traits<::bovespa_mbo_sbe::schema::types::InstrAttribType>
{
public:
    static constexpr const char* name() noexcept
    {
        return "InstrAttribType";
    }

    static constexpr const char* description() noexcept
    {
        return "Code to represent the type of instrument attributes.";
    }

    using encoding_type = ::std::uint8_t;
    
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bovespa_mbo_sbe::types::InstrAttribType;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::types::InstrAttribType>
{
    using type = ::bovespa_mbo_sbe::schema::types::InstrAttribType;
};


template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::InstrAttribType::TRADE_TYPE_ELIGIBILITY>
{
public:
    static constexpr const char* name() noexcept
    {
        return "TRADE_TYPE_ELIGIBILITY";
    }

    static constexpr const char* description() noexcept
    {
        return "Trade type eligibility details for security.";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::InstrAttribType value() noexcept
    {
        return ::bovespa_mbo_sbe::types::InstrAttribType::TRADE_TYPE_ELIGIBILITY;
    }
};

template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::InstrAttribType::GTD_GTC_ELIGIBILITY>
{
public:
    static constexpr const char* name() noexcept
    {
        return "GTD_GTC_ELIGIBILITY";
    }

    static constexpr const char* description() noexcept
    {
        return "Eligibility for GTD/GTC.";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::InstrAttribType value() noexcept
    {
        return ::bovespa_mbo_sbe::types::InstrAttribType::GTD_GTC_ELIGIBILITY;
    }
};

}  // namespace sbepp

SBEPP_WARNINGS_ON();
