// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.3.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bovespa_mbo_sbe
{
namespace detail
{
namespace types
{

class type_60
    : public ::sbepp::detail::required_base<::std::int64_t, type_60>
{
public:
    using ::sbepp::detail::required_base<
        ::std::int64_t, type_60>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {-9223372036854775807};
    }

    static constexpr value_type max_value() noexcept
    {
        return {9223372036854775807};
    }
};

} // namespace types
} // namespace detail

namespace types
{
using Int64 = ::bovespa_mbo_sbe::detail::types::type_60;
} // namespace types
} // namespace bovespa_mbo_sbe

namespace sbepp
{

template<>
class type_traits<::bovespa_mbo_sbe::schema::types::Int64>
{
public:
    static constexpr const char* name() noexcept
    {
        return "Int64";
    }

    static constexpr const char* description() noexcept
    {
        return "8-byte signed integer, from -9223372036854775808 (-2^63) to 9223372036854775807 (2^63-1).";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::int64_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    
    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bovespa_mbo_sbe::types::Int64;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::types::Int64>
{
    using type = ::bovespa_mbo_sbe::schema::types::Int64;
};


}  // namespace sbepp

SBEPP_WARNINGS_ON();
