// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.3.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bovespa_mbo_sbe
{
namespace detail
{
namespace types
{

class type_61
    : public ::sbepp::detail::required_base<::std::uint16_t, type_61>
{
public:
    using ::sbepp::detail::required_base<
        ::std::uint16_t, type_61>::required_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {65534};
    }
};

} // namespace types
} // namespace detail

namespace types
{
using LocalMktDate = ::bovespa_mbo_sbe::detail::types::type_61;
} // namespace types
} // namespace bovespa_mbo_sbe

namespace sbepp
{

template<>
class type_traits<::bovespa_mbo_sbe::schema::types::LocalMktDate>
{
public:
    static constexpr const char* name() noexcept
    {
        return "LocalMktDate";
    }

    static constexpr const char* description() noexcept
    {
        return "Local date (as opposed to UTC). Number of days since UNIX Epoch (January 1st, 1970). Example: 18319 represents February 27, 2020.";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::required;
    }

    using primitive_type = ::std::uint16_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    
    
    static constexpr const char* semantic_type() noexcept
    {
        return "LocalMktDate";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bovespa_mbo_sbe::types::LocalMktDate;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::types::LocalMktDate>
{
    using type = ::bovespa_mbo_sbe::schema::types::LocalMktDate;
};


}  // namespace sbepp

SBEPP_WARNINGS_ON();
