// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.3.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bovespa_mbo_sbe
{
namespace detail
{
namespace types
{

enum class enum_7 : ::std::uint8_t
{
    ODD_LOT = 1,
    ROUND_LOT = 2,
    BLOCK_LOT = 3
};

template<typename Visitor>
SBEPP_CPP14_CONSTEXPR void tag_invoke(
    ::sbepp::detail::visit_tag, enum_7 e, Visitor& visitor) noexcept
{
    switch(e)
    {
    case enum_7::ODD_LOT:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::LotType::ODD_LOT{});
        break;
    case enum_7::ROUND_LOT:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::LotType::ROUND_LOT{});
        break;
    case enum_7::BLOCK_LOT:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::LotType::BLOCK_LOT{});
        break;
    default:
        visitor.on_enum_value(e, ::sbepp::unknown_enum_value_tag{});
    }
}


} // namespace types
} // namespace detail

namespace types
{
using LotType = ::bovespa_mbo_sbe::detail::types::enum_7;
} // namespace types
} // namespace bovespa_mbo_sbe

namespace sbepp
{

template<>
class enum_traits<::bovespa_mbo_sbe::schema::types::LotType>
{
public:
    static constexpr const char* name() noexcept
    {
        return "LotType";
    }

    static constexpr const char* description() noexcept
    {
        return "Describes the lot type for the instruments. Used for the Equities segment.";
    }

    using encoding_type = ::std::uint8_t;
    
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bovespa_mbo_sbe::types::LotType;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::types::LotType>
{
    using type = ::bovespa_mbo_sbe::schema::types::LotType;
};


template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::LotType::ODD_LOT>
{
public:
    static constexpr const char* name() noexcept
    {
        return "ODD_LOT";
    }

    static constexpr const char* description() noexcept
    {
        return "Odd lot.";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::LotType value() noexcept
    {
        return ::bovespa_mbo_sbe::types::LotType::ODD_LOT;
    }
};

template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::LotType::ROUND_LOT>
{
public:
    static constexpr const char* name() noexcept
    {
        return "ROUND_LOT";
    }

    static constexpr const char* description() noexcept
    {
        return "Round lot.";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::LotType value() noexcept
    {
        return ::bovespa_mbo_sbe::types::LotType::ROUND_LOT;
    }
};

template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::LotType::BLOCK_LOT>
{
public:
    static constexpr const char* name() noexcept
    {
        return "BLOCK_LOT";
    }

    static constexpr const char* description() noexcept
    {
        return "Block lot.";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::LotType value() noexcept
    {
        return ::bovespa_mbo_sbe::types::LotType::BLOCK_LOT;
    }
};

}  // namespace sbepp

SBEPP_WARNINGS_ON();
