// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.3.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bovespa_mbo_sbe
{
namespace detail
{
namespace types
{


class type_81
    : public ::sbepp::detail::optional_base<::std::uint16_t, type_81>
{
public:
    using ::sbepp::detail::optional_base<
        ::std::uint16_t, type_81>::optional_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {65534};
    }

    static constexpr value_type null_value() noexcept
    {
        return {0};
    }
};

class type_82
    : public ::sbepp::detail::optional_base<::std::uint8_t, type_82>
{
public:
    using ::sbepp::detail::optional_base<
        ::std::uint8_t, type_82>::optional_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {254};
    }

    static constexpr value_type null_value() noexcept
    {
        return {0};
    }
};

class type_83
    : public ::sbepp::detail::optional_base<::std::uint8_t, type_83>
{
public:
    using ::sbepp::detail::optional_base<
        ::std::uint8_t, type_83>::optional_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {254};
    }

    static constexpr value_type null_value() noexcept
    {
        return {0};
    }
};

class type_84
    : public ::sbepp::detail::optional_base<::std::uint8_t, type_84>
{
public:
    using ::sbepp::detail::optional_base<
        ::std::uint8_t, type_84>::optional_base;

    static constexpr value_type min_value() noexcept
    {
        return {0};
    }

    static constexpr value_type max_value() noexcept
    {
        return {254};
    }

    static constexpr value_type null_value() noexcept
    {
        return {0};
    }
};


template<typename Byte>
class composite_15 : public ::sbepp::detail::composite_base<Byte>
{
public:
    using ::sbepp::detail::composite_base<Byte>::composite_base;
    using ::sbepp::detail::composite_base<Byte>::operator();

    SBEPP_CPP20_CONSTEXPR ::bovespa_mbo_sbe::detail::types::type_81 year() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bovespa_mbo_sbe::detail::types::type_81, ::bovespa_mbo_sbe::detail::types::type_81::value_type, ::sbepp::endian::little>(*this, 0);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void year(::bovespa_mbo_sbe::detail::types::type_81 v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 0, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bovespa_mbo_sbe::detail::types::type_82 month() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bovespa_mbo_sbe::detail::types::type_82, ::bovespa_mbo_sbe::detail::types::type_82::value_type, ::sbepp::endian::little>(*this, 2);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void month(::bovespa_mbo_sbe::detail::types::type_82 v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 2, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bovespa_mbo_sbe::detail::types::type_83 day() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bovespa_mbo_sbe::detail::types::type_83, ::bovespa_mbo_sbe::detail::types::type_83::value_type, ::sbepp::endian::little>(*this, 3);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void day(::bovespa_mbo_sbe::detail::types::type_83 v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 3, v.value());
    }
    SBEPP_CPP20_CONSTEXPR ::bovespa_mbo_sbe::detail::types::type_84 week() const noexcept
    {
        return ::sbepp::detail::get_value<
            ::bovespa_mbo_sbe::detail::types::type_84, ::bovespa_mbo_sbe::detail::types::type_84::value_type, ::sbepp::endian::little>(*this, 4);
    }

    template<
        typename T = void,
        typename = ::sbepp::detail::enable_if_writable_t<Byte, T>>
    SBEPP_CPP20_CONSTEXPR void week(::bovespa_mbo_sbe::detail::types::type_84 v) const noexcept
    {
        ::sbepp::detail::set_value<::sbepp::endian::little>(*this, 4, v.value());
    }


    constexpr std::size_t
        operator()(::sbepp::detail::size_bytes_tag) const noexcept
    {
        return 5;
    }

    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_tag, Visitor& v, Cursor&) const
    {
        return v.template on_composite(*this, ::bovespa_mbo_sbe::schema::types::MaturityMonthYear{});
    }


    template<typename Visitor, typename Cursor>
    constexpr bool operator()(
        ::sbepp::detail::visit_children_tag, Visitor& v, Cursor&) const
    {
        return v.template on_type(this->year(), ::bovespa_mbo_sbe::schema::types::MaturityMonthYear::year{})
||v.template on_type(this->month(), ::bovespa_mbo_sbe::schema::types::MaturityMonthYear::month{})
||v.template on_type(this->day(), ::bovespa_mbo_sbe::schema::types::MaturityMonthYear::day{})
||v.template on_type(this->week(), ::bovespa_mbo_sbe::schema::types::MaturityMonthYear::week{});
    }

};

} // namespace types
} // namespace detail

namespace types
{

    template<typename Byte>
    using MaturityMonthYear = ::bovespa_mbo_sbe::detail::types::composite_15<Byte>;

} // namespace types
} // namespace bovespa_mbo_sbe

namespace sbepp
{

template<>
class type_traits<::bovespa_mbo_sbe::schema::types::MaturityMonthYear::year>
{
public:
    static constexpr const char* name() noexcept
    {
        return "year";
    }

    static constexpr const char* description() noexcept
    {
        return "4-digit year";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::optional;
    }

    using primitive_type = ::std::uint16_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    static constexpr primitive_type null_value() noexcept
    {
        return value_type::null_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {0};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bovespa_mbo_sbe::detail::types::type_81;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::detail::types::type_81>
{
    using type = ::bovespa_mbo_sbe::schema::types::MaturityMonthYear::year;
};


template<>
class type_traits<::bovespa_mbo_sbe::schema::types::MaturityMonthYear::month>
{
public:
    static constexpr const char* name() noexcept
    {
        return "month";
    }

    static constexpr const char* description() noexcept
    {
        return "Month (1 to 12)";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::optional;
    }

    using primitive_type = ::std::uint8_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    static constexpr primitive_type null_value() noexcept
    {
        return value_type::null_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {2};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bovespa_mbo_sbe::detail::types::type_82;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::detail::types::type_82>
{
    using type = ::bovespa_mbo_sbe::schema::types::MaturityMonthYear::month;
};


template<>
class type_traits<::bovespa_mbo_sbe::schema::types::MaturityMonthYear::day>
{
public:
    static constexpr const char* name() noexcept
    {
        return "day";
    }

    static constexpr const char* description() noexcept
    {
        return "Day of month (1 to 31)";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::optional;
    }

    using primitive_type = ::std::uint8_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    static constexpr primitive_type null_value() noexcept
    {
        return value_type::null_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {3};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bovespa_mbo_sbe::detail::types::type_83;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::detail::types::type_83>
{
    using type = ::bovespa_mbo_sbe::schema::types::MaturityMonthYear::day;
};


template<>
class type_traits<::bovespa_mbo_sbe::schema::types::MaturityMonthYear::week>
{
public:
    static constexpr const char* name() noexcept
    {
        return "week";
    }

    static constexpr const char* description() noexcept
    {
        return "Week of month (1 to 5)";
    }

    static constexpr field_presence presence() noexcept
    {
        return ::sbepp::field_presence::optional;
    }

    using primitive_type = ::std::uint8_t;
    
    static constexpr primitive_type min_value() noexcept
    {
        return value_type::min_value();
    }
    
    static constexpr primitive_type max_value() noexcept
    {
        return value_type::max_value();
    }

    static constexpr primitive_type null_value() noexcept
    {
        return value_type::null_value();
    }

    
    static constexpr length_t length() noexcept
    {
        return 1;
    }
    
    static constexpr offset_t offset() noexcept
    {
        return {4};
    }

    
    static constexpr const char* semantic_type() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    static constexpr const char* character_encoding() noexcept
    {
        return "";
    }

    
    using value_type = ::bovespa_mbo_sbe::detail::types::type_84;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::detail::types::type_84>
{
    using type = ::bovespa_mbo_sbe::schema::types::MaturityMonthYear::week;
};


template<>
class composite_traits<::bovespa_mbo_sbe::schema::types::MaturityMonthYear>
{
public:
    static constexpr const char* name() noexcept
    {
        return "MaturityMonthYear";
    }

    static constexpr const char* description() noexcept
    {
        return "Year, Month and Date";
    }

    

    static constexpr const char* semantic_type() noexcept
    {
        return "MonthYear";
    }

    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    
    template<typename Byte>
    using value_type = ::bovespa_mbo_sbe::types::MaturityMonthYear<Byte>;


    static constexpr std::size_t size_bytes() noexcept
    {
        return 5;
    }
};

template<typename Byte>
struct traits_tag<::bovespa_mbo_sbe::types::MaturityMonthYear<Byte>>
{
    using type = ::bovespa_mbo_sbe::schema::types::MaturityMonthYear;
};


}  // namespace sbepp

SBEPP_WARNINGS_ON();
