// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.3.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bovespa_mbo_sbe
{
namespace detail
{
namespace types
{

enum class enum_33 : ::std::uint8_t
{
    PREDEFINED = 0,
    USER_DEFINED = 1
};

template<typename Visitor>
SBEPP_CPP14_CONSTEXPR void tag_invoke(
    ::sbepp::detail::visit_tag, enum_33 e, Visitor& visitor) noexcept
{
    switch(e)
    {
    case enum_33::PREDEFINED:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::MultiLegModel::PREDEFINED{});
        break;
    case enum_33::USER_DEFINED:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::MultiLegModel::USER_DEFINED{});
        break;
    default:
        visitor.on_enum_value(e, ::sbepp::unknown_enum_value_tag{});
    }
}


} // namespace types
} // namespace detail

namespace types
{
using MultiLegModel = ::bovespa_mbo_sbe::detail::types::enum_33;
} // namespace types
} // namespace bovespa_mbo_sbe

namespace sbepp
{

template<>
class enum_traits<::bovespa_mbo_sbe::schema::types::MultiLegModel>
{
public:
    static constexpr const char* name() noexcept
    {
        return "MultiLegModel";
    }

    static constexpr const char* description() noexcept
    {
        return "Specifies the type of multileg order. Defines whether the security is pre-defined or user-defined.";
    }

    using encoding_type = ::std::uint8_t;
    
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bovespa_mbo_sbe::types::MultiLegModel;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::types::MultiLegModel>
{
    using type = ::bovespa_mbo_sbe::schema::types::MultiLegModel;
};


template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::MultiLegModel::PREDEFINED>
{
public:
    static constexpr const char* name() noexcept
    {
        return "PREDEFINED";
    }

    static constexpr const char* description() noexcept
    {
        return "Predefined Multileg Security.";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::MultiLegModel value() noexcept
    {
        return ::bovespa_mbo_sbe::types::MultiLegModel::PREDEFINED;
    }
};

template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::MultiLegModel::USER_DEFINED>
{
public:
    static constexpr const char* name() noexcept
    {
        return "USER_DEFINED";
    }

    static constexpr const char* description() noexcept
    {
        return "User-Defined Multileg Security.";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::MultiLegModel value() noexcept
    {
        return ::bovespa_mbo_sbe::types::MultiLegModel::USER_DEFINED;
    }
};

}  // namespace sbepp

SBEPP_WARNINGS_ON();
