// SPDX-License-Identifier: MIT
// Copyright (c) 2023, Oleksandr Koval

// This file was generated by sbeppc 1.3.0
#pragma once

#include <sbepp/sbepp.hpp>

SBEPP_WARNINGS_OFF();

#include "../schema/schema.hpp"


namespace bovespa_mbo_sbe
{
namespace detail
{
namespace types
{

enum class enum_1 : char
{
    ISIN = '4',
    EXCHANGE_SYMBOL = '8'
};

template<typename Visitor>
SBEPP_CPP14_CONSTEXPR void tag_invoke(
    ::sbepp::detail::visit_tag, enum_1 e, Visitor& visitor) noexcept
{
    switch(e)
    {
    case enum_1::ISIN:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::SecurityIDSource::ISIN{});
        break;
    case enum_1::EXCHANGE_SYMBOL:
        visitor.on_enum_value(e, ::bovespa_mbo_sbe::schema::types::SecurityIDSource::EXCHANGE_SYMBOL{});
        break;
    default:
        visitor.on_enum_value(e, ::sbepp::unknown_enum_value_tag{});
    }
}


} // namespace types
} // namespace detail

namespace types
{
using SecurityIDSource = ::bovespa_mbo_sbe::detail::types::enum_1;
} // namespace types
} // namespace bovespa_mbo_sbe

namespace sbepp
{

template<>
class enum_traits<::bovespa_mbo_sbe::schema::types::SecurityIDSource>
{
public:
    static constexpr const char* name() noexcept
    {
        return "SecurityIDSource";
    }

    static constexpr const char* description() noexcept
    {
        return "Identifies class or source of the SecurityID value.";
    }

    using encoding_type = char;
    
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    
    using value_type = ::bovespa_mbo_sbe::types::SecurityIDSource;
};

template<>
struct traits_tag<::bovespa_mbo_sbe::types::SecurityIDSource>
{
    using type = ::bovespa_mbo_sbe::schema::types::SecurityIDSource;
};


template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::SecurityIDSource::ISIN>
{
public:
    static constexpr const char* name() noexcept
    {
        return "ISIN";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::SecurityIDSource value() noexcept
    {
        return ::bovespa_mbo_sbe::types::SecurityIDSource::ISIN;
    }
};

template<>
class enum_value_traits<::bovespa_mbo_sbe::schema::types::SecurityIDSource::EXCHANGE_SYMBOL>
{
public:
    static constexpr const char* name() noexcept
    {
        return "EXCHANGE_SYMBOL";
    }

    static constexpr const char* description() noexcept
    {
        return "";
    }
    
    static constexpr version_t since_version() noexcept
    {
        return 0;
    }

    

    static constexpr ::bovespa_mbo_sbe::types::SecurityIDSource value() noexcept
    {
        return ::bovespa_mbo_sbe::types::SecurityIDSource::EXCHANGE_SYMBOL;
    }
};

}  // namespace sbepp

SBEPP_WARNINGS_ON();
